package com.example.currencies.requests

import com.example.currencies.CurrenciesApplication
import com.example.currencies.R
import com.example.currencies.utils.csvData

private val context = CurrenciesApplication.getResources()
val codeMap: Map<String, String> = mapOf(
        "AED" to context.getString(R.string.uae_dirham),
        "AFN" to context.getString(R.string.afghan_afghani),
        "ALL" to context.getString(R.string.albanian_lek),
        "AMD" to context.getString(R.string.armenian_dram),
        "ANG" to context.getString(R.string.netherlands_antillian_guilder),
        "AOA" to context.getString(R.string.angolan_kwanza),
        "ARS" to context.getString(R.string.argentine_peso),
        "AUD" to context.getString(R.string.australian_dollar),
        "AWG" to context.getString(R.string.aruban_florin),
        "AZN" to context.getString(R.string.azerbaijani_manat),
        "BAM" to context.getString(R.string.bosnia_herzegovina_convertible_mark),
        "BBD" to context.getString(R.string.barbados_dollar),
        "BDT" to context.getString(R.string.bangladeshi_taka),
        "BGN" to context.getString(R.string.bulgarian_lev),
        "BHD" to context.getString(R.string.bahraini_dinar),
        "BIF" to context.getString(R.string.burundian_franc),
        "BMD" to context.getString(R.string.bermudian_dollar),
        "BND" to context.getString(R.string.brunei_dollar),
        "BOB" to context.getString(R.string.bolivian_boliviano),
        "BRL" to context.getString(R.string.brazilian_real),
        "BSD" to context.getString(R.string.bahamian_dollar),
        "BTN" to context.getString(R.string.bhutanese_ngultrum),
        "BWP" to context.getString(R.string.botswana_pula),
        "BYN" to context.getString(R.string.belarusian_ruble),
        "BZD" to context.getString(R.string.belize_dollar),
        "CAD" to context.getString(R.string.canadian_dollar),
        "CDF" to context.getString(R.string.congolese_franc),
        "CHF" to context.getString(R.string.swiss_franc),
        "CLP" to context.getString(R.string.chilean_peso),
        "CNY" to context.getString(R.string.chinese_renminbi),
        "COP" to context.getString(R.string.colombian_peso),
        "CRC" to context.getString(R.string.costa_rican_colon),
        "CUP" to context.getString(R.string.cuban_peso),
        "CVE" to context.getString(R.string.cape_verdean_escudo),
        "CZK" to context.getString(R.string.czech_koruna),
        "DJF" to context.getString(R.string.djiboutian_franc),
        "DKK" to context.getString(R.string.danish_krone),
        "DOP" to context.getString(R.string.dominican_peso),
        "DZD" to context.getString(R.string.algerian_dinar),
        "EGP" to context.getString(R.string.egyptian_pound),
        "ERN" to context.getString(R.string.eritrean_nakfa),
        "ETB" to context.getString(R.string.ethiopian_birr),
        "EUR" to context.getString(R.string.euro),
        "FJD" to context.getString(R.string.fiji_dollar),
        "FKP" to context.getString(R.string.falkland_islands_pound),
        "FOK" to context.getString(R.string.faroese_krona),
        "GBP" to context.getString(R.string.pound_sterling),
        "GEL" to context.getString(R.string.georgian_lari),
        "GGP" to context.getString(R.string.guernsey_pound),
        "GHS" to context.getString(R.string.ghanaian_cedi),
        "GIP" to context.getString(R.string.gibraltar_pound),
        "GMD" to context.getString(R.string.gambian_dalasi),
        "GNF" to context.getString(R.string.guinean_franc),
        "GTQ" to context.getString(R.string.guatemalan_quetzal),
        "GYD" to context.getString(R.string.guyanese_dollar),
        "HKD" to context.getString(R.string.hong_kong_dollar),
        "HNL" to context.getString(R.string.honduran_lempira),
        "HRK" to context.getString(R.string.croatian_kuna),
        "HTG" to context.getString(R.string.haitian_gourde),
        "HUF" to context.getString(R.string.hungarian_forint),
        "IDR" to context.getString(R.string.indonesian_rupiah),
        "ILS" to context.getString(R.string.israeli_new_shekel),
        "IMP" to context.getString(R.string.manx_pound),
        "INR" to context.getString(R.string.indian_rupee),
        "IQD" to context.getString(R.string.iraqi_dinar),
        "IRR" to context.getString(R.string.iranian_rial),
        "ISK" to context.getString(R.string.icelandic_krona),
        "JEP" to context.getString(R.string.jersey_pound),
        "JMD" to context.getString(R.string.jamaican_dollar),
        "JOD" to context.getString(R.string.jordanian_dinar),
        "JPY" to context.getString(R.string.japanese_yen),
        "KES" to context.getString(R.string.kenyan_shilling),
        "KGS" to context.getString(R.string.kyrgyzstani_som),
        "KHR" to context.getString(R.string.cambodian_riel),
        "KID" to context.getString(R.string.kiribati_dollar),
        "KMF" to context.getString(R.string.comorian_franc),
        "KRW" to context.getString(R.string.south_korean_won),
        "KWD" to context.getString(R.string.kuwaiti_dinar),
        "KYD" to context.getString(R.string.cayman_islands_dollar),
        "KZT" to context.getString(R.string.kazakhstani_tenge),
        "LAK" to context.getString(R.string.lao_kip),
        "LBP" to context.getString(R.string.lebanese_pound),
        "LKR" to context.getString(R.string.sri_lanka_rupee),
        "LRD" to context.getString(R.string.liberian_dollar),
        "LSL" to context.getString(R.string.lesotho_loti),
        "LYD" to context.getString(R.string.libyan_dinar),
        "MAD" to context.getString(R.string.moroccan_dirham),
        "MDL" to context.getString(R.string.moldovan_leu),
        "MGA" to context.getString(R.string.malagasy_ariary),
        "MKD" to context.getString(R.string.macedonian_denar),
        "MMK" to context.getString(R.string.burmese_kyat),
        "MNT" to context.getString(R.string.mongolian_togrog),
        "MOP" to context.getString(R.string.macanese_pataca),
        "MRU" to context.getString(R.string.mauritanian_ouguiya),
        "MUR" to context.getString(R.string.mauritian_rupee),
        "MVR" to context.getString(R.string.maldivian_rufiyaa),
        "MWK" to context.getString(R.string.malawian_kwacha),
        "MXN" to context.getString(R.string.mexican_peso),
        "MYR" to context.getString(R.string.malaysian_ringgit),
        "MZN" to context.getString(R.string.mozambican_metical),
        "NAD" to context.getString(R.string.namibian_dollar),
        "NGN" to context.getString(R.string.nigerian_naira),
        "NIO" to context.getString(R.string.nicaraguan_cordoba),
        "NOK" to context.getString(R.string.norwegian_krone),
        "NPR" to context.getString(R.string.nepalese_rupee),
        "NZD" to context.getString(R.string.new_zealand_dollar),
        "OMR" to context.getString(R.string.omani_rial),
        "PAB" to context.getString(R.string.panamanian_balboa),
        "PEN" to context.getString(R.string.peruvian_sol),
        "PGK" to context.getString(R.string.papua_new_guinean_kina),
        "PHP" to context.getString(R.string.philippine_peso),
        "PKR" to context.getString(R.string.pakistani_rupee),
        "PLN" to context.getString(R.string.polish_zloty),
        "PYG" to context.getString(R.string.paraguayan_guarani),
        "QAR" to context.getString(R.string.qatari_riyal),
        "RON" to context.getString(R.string.romanian_leu),
        "RSD" to context.getString(R.string.serbian_dinar),
        "RUB" to context.getString(R.string.russian_ruble),
        "RWF" to context.getString(R.string.rwandan_franc),
        "SAR" to context.getString(R.string.saudi_riyal),
        "SBD" to context.getString(R.string.solomon_islands_dollar),
        "SCR" to context.getString(R.string.seychellois_rupee),
        "SDG" to context.getString(R.string.sudanese_pound),
        "SEK" to context.getString(R.string.swedish_krona),
        "SGD" to context.getString(R.string.singapore_dollar),
        "SHP" to context.getString(R.string.saint_helena_pound),
        "SLE" to context.getString(R.string.sierra_leonean_leone),
        "SLL" to context.getString(R.string.sierra_leonean_leone),
        "SOS" to context.getString(R.string.somali_shilling),
        "SRD" to context.getString(R.string.surinamese_dollar),
        "SSP" to context.getString(R.string.south_sudanese_pound),
        "STN" to context.getString(R.string.sao_tome_principe_dobra),
        "SYP" to context.getString(R.string.syrian_pound),
        "SZL" to context.getString(R.string.eswatini_lilangeni),
        "THB" to context.getString(R.string.thai_baht),
        "TJS" to context.getString(R.string.tajikistani_somoni),
        "TMT" to context.getString(R.string.turkmenistan_manat),
        "TND" to context.getString(R.string.tunisian_dinar),
        "TOP" to context.getString(R.string.tongan_paanga),
        "TRY" to context.getString(R.string.turkish_lira),
        "TTD" to context.getString(R.string.trinidad_tobago_dollar),
        "TVD" to context.getString(R.string.tuvaluan_dollar),
        "TWD" to context.getString(R.string.new_taiwan_dollar),
        "TZS" to context.getString(R.string.tanzanian_shilling),
        "UAH" to context.getString(R.string.ukrainian_hryvnia),
        "UGX" to context.getString(R.string.ugandan_shilling),
        "USD" to context.getString(R.string.united_states_dollar),
        "UYU" to context.getString(R.string.uruguayan_peso),
        "UZS" to context.getString(R.string.uzbekistani_som),
        "VES" to context.getString(R.string.venezuelan_bolivar),
        "VND" to context.getString(R.string.vietnamese_dong),
        "VUV" to context.getString(R.string.vanuatu_vatu),
        "WST" to context.getString(R.string.samoan_tala),
        "XAF" to context.getString(R.string.central_african_cfa_franc),
        "XCD" to context.getString(R.string.east_caribbean_dollar),
        "XCG" to context.getString(R.string.caribbean_guilder),
        "XDR" to context.getString(R.string.special_drawing_rights),
        "XOF" to context.getString(R.string.west_african_cfa_franc),
        "XPF" to context.getString(R.string.cfp_franc),
        "YER" to context.getString(R.string.yemeni_rial),
        "ZAR" to context.getString(R.string.south_african_rand),
        "ZMW" to context.getString(R.string.zambian_kwacha),
        "ZWL" to context.getString(R.string.zimbabwean_dollar)
    )
val currencyCodes: Map<String, Triple<String, String, Int>> = mockCurrencyCodes()


private fun mockCurrencyCodes(): Map<String, Triple<String, String, Int>> {
    val currencyCodes: MutableMap<String, Triple<String, String, Int>> = mutableMapOf()
    if (currencyCodes.isNotEmpty()) {
        return currencyCodes
    }
    val csvData: Map<String, Pair<String, String>> = csvData
    for (code in codeMap) {
        val codeKey = code.key
        if (csvData.containsKey(codeKey)) {
            val country = csvData[codeKey]?.first ?: continue
            val continent = csvData[codeKey]?.second ?: continue
            val codeImage = CurrenciesApplication.getResources().getIdentifier(
                country.lowercase(),
                "drawable",
                "com.example.currencies",
            )
            currencyCodes[codeKey] = Triple(continent, code.value, codeImage)
        }
    }

        return currencyCodes.entries
                .sortedBy { it.value.first }
                .associate { it.key to it.value }
}

